name: Alerte Pass Logement

on:
  schedule:
    - cron: '*/5 * * * *'  # Toutes les 5 minutes
  workflow_dispatch:

jobs:
  alerte-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Autorise les pushs dans le repo

    env:
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
      TO_PHONE: ${{ secrets.TO_PHONE }}

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Exécuter le script
      run: python alertePassLogement.py

    - name: Commit & Push des nouvelles offres
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull
        git add old_offers.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour automatique des offres"
        git push
